<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cs" nsURI="http://www.example.org/cs" nsPrefix="cs">
  <eClassifiers xsi:type="ecore:EClass" name="Serveur" eSuperTypes="cosa.ecore#//Configuration">
    <eOperations name="receptionRequeteClient"/>
    <eOperations name="reponseRequeteClient"/>
    <eOperations name="reponseRequeteConnectionM"/>
    <eOperations name="envoieRequeteConnectionM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portrequisserveur" lowerBound="1"
        eType="#//PortRequisServeur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portfourniserveur" lowerBound="1"
        eType="#//PortFourniServeur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionmanager" lowerBound="1"
        eType="#//ConnectionManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securitymanager" lowerBound="1"
        eType="#//SecurityManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//DataBase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlquery" lowerBound="1"
        eType="#//SQLquery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityquery" lowerBound="1"
        eType="#//SecurityQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clearancerequest" lowerBound="1"
        eType="#//ClearanceRequest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachconnectionsql" lowerBound="1"
        eType="#//AttachCONNECTIONsql"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachdbsql" lowerBound="1"
        eType="#//AttachDBsql"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachdbsecurity" lowerBound="1"
        eType="#//AttachDBsecurity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachsecuritysecurity"
        lowerBound="1" eType="#//AttachSECURITYsecurity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachconnectionclearance"
        lowerBound="1" eType="#//AttachCONNECTIONclearance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachsecurityclearance"
        lowerBound="1" eType="#//AttachSECURITYclearance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingserveurconnectionm"
        lowerBound="1" eType="#//BindingServeurConnectionM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortRequisServeur" eSuperTypes="cosa.ecore#//PortRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortFourniServeur" eSuperTypes="cosa.ecore#//PortFourni"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionManager" eSuperTypes="cosa.ecore#//EComposant">
    <eOperations name="receptionRequeteServeur"/>
    <eOperations name="envoieRequeteDataBase"/>
    <eOperations name="receptionRequeteDataBase"/>
    <eOperations name="envoieRequeteServeur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portrequisserveurcm" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portrequisdatabasecm" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityManager" eSuperTypes="cosa.ecore#//EComposant"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataBase" eSuperTypes="cosa.ecore#//EComposant">
    <eOperations/>
    <eOperations/>
    <eOperations/>
    <eOperations/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLquery" eSuperTypes="cosa.ecore#//EConnecteur">
    <eOperations/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlueSQLquery" eSuperTypes="cosa.ecore#//Glue">
    <eOperations/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityQuery" eSuperTypes="cosa.ecore#//EConnecteur">
    <eOperations/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlueSecurityRequest" eSuperTypes="cosa.ecore#//Glue">
    <eOperations/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClearanceRequest" eSuperTypes="cosa.ecore#//EConnecteur">
    <eOperations/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlueClearanceRequest" eSuperTypes="cosa.ecore#//Glue">
    <eOperations/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachCONNECTIONsql" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachDBsql" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachDBsecurity" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachSECURITYsecurity" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachCONNECTIONclearance" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachSECURITYclearance" eSuperTypes="cosa.ecore#//Attachment">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingServeurConnectionM" eSuperTypes="cosa.ecore#//Binding">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="cosa.ecore#//EComposant">
    <eOperations name="envoieRequeteClient"/>
    <eOperations name="receptionRequeteClient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portrequisclient" lowerBound="1"
        eType="#//PortRequisClient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portfournisclient" lowerBound="1"
        eType="#//PortFourniClient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortRequisClient" eSuperTypes="cosa.ecore#//PortRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortFourniClient" eSuperTypes="cosa.ecore#//PortFourni"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPC" eSuperTypes="cosa.ecore#//EConnecteur">
    <eOperations name="transfertMessageRPC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gluerpc" lowerBound="1"
        eType="#//GlueRPC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rolerequisclient" lowerBound="1"
        eType="#//RoleRequisRPC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rolerequisserveur" lowerBound="1"
        eType="#//RoleRequisRPC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rolefourniclient" lowerBound="1"
        eType="#//RoleFourniRPC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rolefourniserveur" lowerBound="1"
        eType="#//RoleRequisRPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlueRPC" eSuperTypes="cosa.ecore#//Glue">
    <eOperations name="matchRoles" eType="ecore:EClass cosa.ecore#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRequisRPC" eSuperTypes="cosa.ecore#//RoleRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleFourniRPC" eSuperTypes="cosa.ecore#//RoleFourni"/>
</ecore:EPackage>
